### PR TITLE
GitHub Actions - Build and create release with packages

### PR DESCRIPTION
**Pull request by cboulay**
I don't think this is ready to merge. I'm making a PR out of this to test triggering the build and artifact uploads.

### CODE REVIEW

**Comment by cboulay** [comment]
@tstenner I can't recall. Does actions/download-artifact unpack the zip files it downloads?

I'm unable to attach the build files to the release, even though they've been correctly downloaded from artifacts.

In any case, I think I'll have to setup the CPack config.

**Comment by cboulay** [comment]
I thought I posted a message updating the status of this but I don't see it. I'm sorry if it is double posted somehow.

This PR is now ready for review. Please look at the auto-generated release to make sure it is satisfactory.

One of the main reasons for putting this together is because I want to be able to download and install libxdf from build scripts, and then use it in a cmake project with a simple `find_package(libxdf)`.

I've updated the README to reflect this workflow. Please have a look in the fork: https://github.com/xdf-modules/libxdf/tree/github_actions

And of course there are other benefits to having a working CI system - maybe we can get some unit tests?

**Comment by Yida-Lin** [comment]
@cboulay Thank you so much for setting up actions, looks fantastic!

I wonder whether win32 release is needed? Last time I checked I think on Windows SigViewer still didn't build with 64 bit due to libbiosig issue, but I am not 100% sure. @cbrnr 

Otherwise it looks very good!

**Review by Yida-Lin — APPROVED** [review]

**Comment by cbrnr** [comment]
I wouldn't release win32 either - I don't know if it's still necessary for SigViewer, but if so I can always build it myself.

**Comment by cbrnr** [comment]
I don't have the time to review or test this, but if you guys find that everything works feel free to go ahead!

**Comment by cboulay** [comment]
I've added Win32 builds to the CI and created a new release.
Let me know if you want me to setup a CI for SigViewer (while the workflow is fresh in mind).

**Comment by cbrnr** [comment]
A CI for SigViewer would indeed be great! However, keep in mind that libxdf if only one out of two dependencies. The other one is libbiosig, which I never managed to build on Windows (unless in a Cygwin/MinGW-like env). If this is feasible, I'd be very happy if you set this up.

**Comment by cboulay** [comment]
I just looked into libbiosig and I think it would take a moderate amount of work to setup a consistent cross-platform build system for SigViewer, one that would download the pre-existing binaries. I'll keep it in the back of my mind but I don't think I can get to it now.

Anyway, this PR is good to go.

**Pull request merged**
